### ISSUE TITLE
Tracker is not defined

### ISSUE THREAD

**Issue by blntylmn** [ssr-server/ssr#1] opened 2017-01-25 10:55 UTC
Hi,
good job!
Everything seems to work but I'm getting this error on the browser console.

![screen shot 2017-01-25 at 13 45 29](https://cloud.githubusercontent.com/assets/15238168/22287948/821106e8-e2fd-11e6-8f45-05a92a67c677.png)

**Comment by cbilotta** [comment] 2017-01-25 10:56
Hello !
Can you send me the code where you use Tracker ?

**Comment by blntylmn** [comment] 2017-01-25 10:58
Don't know. This is just your demo project :)

**Comment by cbilotta** [comment] 2017-01-25 11:02
Have you run meteor yarn install on both the root folder and the demo folder ? You need to do it in both for the demo to work!

**Comment by blntylmn** [comment] 2017-01-25 11:05
"meteor yarn install" gives me an error like this 
-'yarn' is not a Meteor command. See 'meteor --help'.
So I run just "yarn install" both of them ( root an demo folder).

**Comment by cbilotta** [comment] 2017-01-25 11:18
You need to install it first. Meteor npm i -g yarn

**Comment by blntylmn** [comment] 2017-01-25 11:38
it was my fault then :( After a long time I returned to the meteor. So I didn't know I have to install separate "yarn" for meteor. So here is the steps what I did.

***ATTEMPT ONE***
1) "meteor npm i -g yarn"
2) "meteor yarn install" for both folders (root & demo)
3) run with "meteor" again
4) nothing changed error was still there
***FAILED***

So I thought maybe something gone wrong at the first install without meteor part "yarn install".

***ATTEMPT TWO***
1) "re clone" the repo for clean install
2) "meteor yarn install" for both folders (root & demo)
3) run with "meteor" again
4) nothing changed error is still there
***FAILED***
![screen shot 2017-01-25 at 14 39 16](https://cloud.githubusercontent.com/assets/15238168/22289337/b64b014c-e303-11e6-84eb-abbafe9f9827.png)

**Comment by PEM--** [comment] 2017-01-25 12:08
```
meteor --settings ./settings.json
```

**Comment by PEM--** [comment] 2017-01-25 12:18
Package order issue, I've circumvented it by forcing the load order of `mongo` and `tracker` at the package level.  I've also updated the docs for running the demo with the settings.

I'm publishing a 1.4.1 in case that would happen on my production projects. Deployments could suffer from these cases.

Thanks for reporting this issue.

**Comment by blntylmn** [comment] 2017-01-25 12:28
Yeap. Worked in 1.4.1.
Btw it is painful writing "meteor --settings settings.json" everytime.
What about this :
![screen shot 2017-01-25 at 15 20 53](https://cloud.githubusercontent.com/assets/15238168/22290494/cf6a1a2c-e309-11e6-9eae-c50b11092f1a.png)
and then just 
**"yarn meteor"**

**Comment by PEM--** [comment] 2017-01-25 12:53
OK, I get it and succeed to reproduce it.

When Meteor dev tools is opened and you load the App, `meteor-devtools` is crashing. This is the reason why you got an error at the `VM` and neither at the package level nor the demo level.

If you start a new tab, load the app and, only then, you go in the  `meteor-devtools`,  `meteor-devtools` doesn't crash anymore.

Note that despite having an issue reported by  `meteor-devtools`, the demo and the package are still working. Chrome isolates the error.

For your suggestion, that would be a nice 1st contribution and with an update on the README, it would be very welcomed.

**Comment by PEM--** [comment] 2017-01-25 13:04
See https://github.com/bakery/meteor-devtools/issues/61

**Comment by PEM--** [comment] 2017-01-25 13:06
@blntylmn I'm closing the issue as there's nothing more to say about it.

**Closed as completed by PEM--** 2017-01-25 13:06 UTC

**Comment by blntylmn** [comment] 2017-01-25 13:19
Ok I also noticed when the console is closed there is no issue. Thanks anyway. I made a pull request for reducing the application start code.

**Comment by PEM--** [comment] 2017-01-25 13:22
Actually, the demo doesn't use `Tracker` at the time being. @iRayzer or me will add a reconciliation based on pub/sub as an example in the demo. The case will disappear 😉
